DROP TABLE BOARD;

CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(1000) NOT NULL,
	WRITER VARCHAR(100) NOT NULL,
	COUNT INT DEFAULT 0,
	INDATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('나 의천인데 나만 다들 바라봤으면 좋겠다','내가 주인공이니까♥','조의천');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('어서빨리 금요일','희망이 살아있다!','익명의 조의천');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('고양이가 하는 말','고양고양고양','최강고양이');

COMMIT;

SELECT * FROM BOARD;
