DROP TABLE 교육생정보 ; 
DROP TABLE 성적표 ; 

CREATE TABLE 교육생정보 (
학생ID VARCHAR2(9) PRIMARY KEY , 
학생이름 VARCHAR2(50) NOT NULL , 
팀 VARCHAR2(5) 
); 

CREATE TABLE 성적표 ( 
    학생ID VARCHAR2(9) , 
    과목   VARCHAR2(30) , 
    성적   NUMBER  , 
    CONSTRAINT PK_성적표 PRIMARY KEY(학생ID , 과목) , 
    CONSTRAINT FK_성적표 FOREIGN KEY(학생ID) REFERENCES 교육생정보(학생ID) 
)  ; 

INSERT INTO 교육생정보 VALUES ('SMHRD1' , '박수현' , 'A') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD2' , '박지승' , 'A') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD3' , '김중진' , 'A') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD4' , '강은혜' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD5' , '이수정' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD6' , '김승화' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD7' , '강승표' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD8' , '장태양' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD9' , '이범석' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD10' , '김소형' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD11' , '김선용' , 'B') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD12' , '김길현' , 'C') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD13' , '김태진' , 'C') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD14' , '허지훈' , 'C') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD15' , '박준혁' , 'C') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD16' , '김민정' , 'C') ; 
INSERT INTO 교육생정보 VALUES ('SMHRD17' , '문지우' , 'C') ; 

INSERT INTO 성적표 VALUES('SMHRD1'  ,'JAVA' , 90); 
INSERT INTO 성적표 VALUES('SMHRD1'  ,'DATABASE' , 85); 
INSERT INTO 성적표 VALUES('SMHRD1'  ,'PYTHON' , 100); 
INSERT INTO 성적표 VALUES('SMHRD2'  ,'JAVA' , 100); 
INSERT INTO 성적표 VALUES('SMHRD2'  ,'DATABASE' , 100); 
INSERT INTO 성적표 VALUES('SMHRD2'  ,'PYTHON' , 20); 
INSERT INTO 성적표 VALUES('SMHRD3'  ,'JAVA' , 100); 
INSERT INTO 성적표 VALUES('SMHRD3'  ,'DATABASE' , 100); 
INSERT INTO 성적표 VALUES('SMHRD3'  ,'PYTHON' , 20); 
INSERT INTO 성적표 VALUES('SMHRD4'  ,'JAVA' , 85); 
INSERT INTO 성적표 VALUES('SMHRD4'  ,'DATABASE' , 40); 
INSERT INTO 성적표 VALUES('SMHRD4'  ,'PYTHON' , 60); 
INSERT INTO 성적표 VALUES('SMHRD5'  ,'JAVA' , 100); 
INSERT INTO 성적표 VALUES('SMHRD5'  ,'DATABASE' , 100); 
INSERT INTO 성적표 VALUES('SMHRD5'  ,'PYTHON' , 100); 
INSERT INTO 성적표 VALUES ( 'SMHRD6' , 'JAVA' , NULL ) ; 
INSERT INTO 성적표 VALUES ( 'SMHRD6' , 'DATABASE' , NULL ) ; 
INSERT INTO 성적표 VALUES ( 'SMHRD6' , 'PYTHON' , NULL ) ; 
INSERT INTO 성적표 VALUES('SMHRD7'  ,'JAVA' , 80); 
INSERT INTO 성적표 VALUES('SMHRD7'  ,'DATABASE' , 90); 
INSERT INTO 성적표 VALUES('SMHRD7'  ,'PYTHON' , 100); 
INSERT INTO 성적표 VALUES('SMHRD8'  ,'JAVA' , 100); 
INSERT INTO 성적표 VALUES('SMHRD8'  ,'DATABASE' , 70); 
INSERT INTO 성적표 VALUES('SMHRD8'  ,'PYTHON' , 85); 
INSERT INTO 성적표 VALUES('SMHRD9'  ,'JAVA' , 95); 
INSERT INTO 성적표 VALUES('SMHRD9'  ,'DATABASE' , 85); 
INSERT INTO 성적표 VALUES('SMHRD9'  ,'PYTHON' , 95); 
INSERT INTO 성적표 VALUES('SMHRD10'  ,'JAVA' , 95); 
INSERT INTO 성적표 VALUES('SMHRD10'  ,'DATABASE' , 95); 
INSERT INTO 성적표 VALUES('SMHRD10'  ,'PYTHON' , 75); 
INSERT INTO 성적표 VALUES('SMHRD11'  ,'JAVA' , 88); 
INSERT INTO 성적표 VALUES('SMHRD11'  ,'DATABASE' , 96); 
INSERT INTO 성적표 VALUES('SMHRD11'  ,'PYTHON' , 56); 
INSERT INTO 성적표 VALUES('SMHRD12'  ,'JAVA' , 94); 
INSERT INTO 성적표 VALUES('SMHRD12'  ,'DATABASE' , 84); 
INSERT INTO 성적표 VALUES('SMHRD12'  ,'PYTHON' , 69); 
INSERT INTO 성적표 VALUES('SMHRD13'  ,'JAVA' , 96); 
INSERT INTO 성적표 VALUES('SMHRD13'  ,'DATABASE' , 92); 
INSERT INTO 성적표 VALUES('SMHRD13'  ,'PYTHON' , 95);
INSERT INTO 성적표 VALUES('SMHRD14'  ,'JAVA' , 78); 
INSERT INTO 성적표 VALUES('SMHRD14'  ,'DATABASE' , 99); 
INSERT INTO 성적표 VALUES('SMHRD14'  ,'PYTHON' , 45);
INSERT INTO 성적표 VALUES('SMHRD15'  ,'JAVA' , 84); 
INSERT INTO 성적표 VALUES('SMHRD15'  ,'DATABASE' , 93); 
INSERT INTO 성적표 VALUES('SMHRD15'  ,'PYTHON' , 81);   
INSERT INTO 성적표 VALUES('SMHRD16'  ,'JAVA' , 65); 
INSERT INTO 성적표 VALUES('SMHRD16'  ,'DATABASE' , 84); 
INSERT INTO 성적표 VALUES('SMHRD16'  ,'PYTHON' , 81); 
INSERT INTO 성적표 VALUES('SMHRD17'  ,'JAVA' , 78); 
INSERT INTO 성적표 VALUES('SMHRD17'  ,'DATABASE' , 95); 
INSERT INTO 성적표 VALUES('SMHRD17'  ,'PYTHON' , 85); 
COMMIT; 
